# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
TEMPLATE = subdirs
SUBDIRS += vKeyboard/vKeyboard.pro \
           CTTester/CTTester.pro
