# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.


HEADERS += ./keyboarddemo.h \
    ./application.h
SOURCES += ./main.cpp \
    ./keyboarddemo.cpp \
    ./application.cpp
FORMS += ./keyboarddemo.ui
RESOURCES += keyboarddemo.qrc
